awk_task:
  freebsd_instance:
    image: freebsd-12-0-release-amd64
  check_script:
    - ./run-tests.sh
gawk_task:
  freebsd_instance:
    image: freebsd-12-0-release-amd64
  install_script: pkg install -y gawk
  check_script:
    - env AWK=/usr/local/bin/gawk ./run-tests.sh
